directories:
  - name: pytorch-practice
    rule: build_rule
  - name: mcmd
    rule: build_rule
  - name: mtest
    rule: python_rule

build_rule:
  - make purge
  - make sdc
  - make install

python_rule:
#  - export build_TEST=1
  - make purge2
  - make sdc2
  - make install2
